### ISSUE TITLE
Reliability issues on Digital Ocean App Engine?

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/fgsea-service#1]
The FGSEA service fails randomly when running on DO App Engine.  This causes the live demo of the app (https://app.em.baderlab.org) to often fail when submitting a query.

The panel on DO says that the service sometimes restarts itself many times when a query is sent in.  This causes the client to time out, as the query is never fulfilled.

We need to track down the cause of the issue to determine mitigations.  Let's use this issue to keep a running log of our hypotheses and updates.

Possibilities:

(1) Hypothesis:  DO App Engine doesn't work well with Docker R images.  
- Test:  Run the service on a plain DO VM.
- Test:  Run locally with many queries overnight, e.g. 1 query / 5 min.
- Mitigation:  Deploy manually to a VM.  Maybe the service doesn't need to be updated often anyway.  It shouldn't really change once it's 'finished'.
- Mitigation:  Deploy to another service, like Render or Google Cloud Run.

(2) Hypothesis:  R just isn't reliable.  Maybe it's good for one-off scripts, but it could be that it's just not up to the task of hosting a reliable service.
- Test: TBD
- Mitigation:  Use a framework like [Crow](https://github.com/CrowCpp/Crow) to directly expose the C++ implementation of FGSEA as a service.

**Comment by maxkfranz** [comment]
Increase RAM on DO App instance

**Comment by maxkfranz** [comment]
App Platform limitations:

- 100 MB file upload max.
- 100s max. request timeout

**Comment by maxkfranz** [comment]
Options:

(1) Manual VM
- Pro: Most control
- Con: Highest maintenance cost

(2) VM with [Easypanel](https://easypanel.io/docs)
- Pro: More control than App Engine
- Pro: Like App Engine & Caprover, but unlike Caprover it's maintained by a commercial org.
- Pro: Most of the benefits of app engine, for services only (not DB)
- Con: A bit higher maintenance than App Engine

(3) Other PaaS, e.g. [Render](https://render.com)
- Pro: Minimal maintenance cost, like DO App Engine
- Con: Most don't have managed MongoDB
- Con: May have similar limitations as App Engine, since it's primarily for the same use case (i.e. quick, CRUD services)

**Comment by mikekucera** [comment]
Not using digital ocean anymore
